occapi_client.occapi_provider.*:
  type: config_entity
  label: OCCAPI provider
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    base_url:
      type: string
      label: 'Base URL'
    hei_id:
      type: string
      label: 'Institution SCHAC code'
    ounit_filter:
      type: boolean
      label: 'Filter by Organizational Unit'
    uuid:
      type: string
    description:
      type: string
