<?php

/**
 * @file
 * Contains occapi_entities_bridge.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function occapi_entities_bridge_occapi_provider_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  if ($operation == 'preview') {
    // Check if the Institution is present in the system.
    $exists = \Drupal::service('entity_type.manager')
      ->getStorage('hei')
      ->loadByProperties(['hei_id' => $entity->get('hei_id')]);

    if (empty($exists)) {
      \Drupal::service('messenger')->addWarning($result['message']);
    }
  }
}

/**
 * Implements hook_base_field_info().
 *
 * Add new base fields to the OCCAPI entity types to store remote API data.
 */
function occapi_entities_bridge_entity_base_field_info(EntityTypeInterface $entity_type) {
  if (in_array($entity_type->id(), ['programme', 'course'])) {
    $remote_data = \Drupal::service('occapi_entities_bridge.remote');
    return $remote_data->attachBaseFields($entity_type);
  }
}

/**
 * Implements hook_entity_type_build().
 *
 * Add new forms and links to the Programmes and Courses.
 */
function occapi_entities_bridge_entity_type_build(array &$entity_types) {
  $remote_data = \Drupal::service('occapi_entities_bridge.remote');
  $remote_data->addEntityForms($entity_types);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function occapi_entities_bridge_form_course_add_form_alter(&$form, FormStateInterface $form_state) {
  _occapi_entities_bridge_api_fields($form, $form_state);
  _occapi_entities_bridge_api_metadata($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function occapi_entities_bridge_form_course_edit_form_alter(&$form, FormStateInterface $form_state) {
  _occapi_entities_bridge_api_fields($form, $form_state);
  _occapi_entities_bridge_api_metadata($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function occapi_entities_bridge_form_programme_add_form_alter(&$form, FormStateInterface $form_state) {
  _occapi_entities_bridge_api_fields($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function occapi_entities_bridge_form_programme_edit_form_alter(&$form, FormStateInterface $form_state) {
  _occapi_entities_bridge_api_fields($form, $form_state);
}

/**
 * Performs the actual form alter for the common fields.
 */
function _occapi_entities_bridge_api_fields(&$form, FormStateInterface $form_state) {
  $remote_data = \Drupal::service('occapi_entities_bridge.remote');
  $remote_data->apiFieldsFormAlter($form, $form_state);
}

/**
 * Performs the actual form alter for the Course metadata field.
 */
function _occapi_entities_bridge_api_metadata(&$form, FormStateInterface $form_state) {
  $remote_data = \Drupal::service('occapi_entities_bridge.remote');
  $remote_data->apiMetadataFormAlter($form, $form_state);
}
